---
- name: copy the patched init script
  copy:
    src=sensu-{{ item }}
    dest=/etc/init.d/
    owner=root
    group=root
    mode=755
    backup=yes
  with_items:
    - server
    - api

- name: ensure the patched init script are used
  command: /usr/sbin/update-rc.d -f sensu-{{ item }} remove && /usr/sbin/update-rc.d sensu-{{ item }} defaults
  with_items:
    - server
    - api

- name: enable sensu-{server,api} to survive reboot
  service: name=sensu-{{ item }} enabled=yes
  with_items:
    - server
    - api

- name: generate config files
  template:
    src={{ item }}.json.j2
    dest=/etc/sensu/conf.d/{{ item }}.json
    owner=sensu
    group=sensu
    mode=0750
  with_items:
    - checks
    - handlers
    - redis
    - api
    
  notify:
    - restart sensu server
    - restart sensu client
